StanfordASL/neural-network-lyapunov

neural_network_lyapunov/examples/quadrotor3d/train_quadrotor_demo.py
neural_network_lyapunov/test/test_train_lyapunov.py
neural_network_lyapunov/train_lyapunov.py

Also change the PoolSolutionMode for the 3D quadrotor from 1 to 0 (default).

Fix a bug that I forgot to reconstruct the optimizer in the trainer after each verification.

---

neural_network_lyapunov/relu_to_optimization.py
neural_network_lyapunov/test/test_relu_to_optimization.py

This would give tighter M in the big-M formulation.

Compute the big-M bounds in output_gradient_times_vec() through optimization

---

neural_network_lyapunov/examples/tinydiffsim/cfg/cartpole.yml
neural_network_lyapunov/examples/tinydiffsim/learn_ca_dyn.py
neural_network_lyapunov/urdf/cartpole.urdf

Need to add explicit support for second order systems. Will also add ray.tune support.

simple training of control affine model using tiny differentiable sim

---

neural_network_lyapunov/mip_utils.py
neural_network_lyapunov/relu_to_optimization.py
neural_network_lyapunov/test/test_relu_to_optimization.py

First propagate the bounds by IA, and then tighten the bounds by MIP.
Note that the bounds gradient is incorrect if the bounds can't be active.

Propagate bounds with IA_MIP.

---

neural_network_lyapunov/control_affine_system.py
neural_network_lyapunov/test/test_control_affine_system.py
neural_network_lyapunov/train_utils.py

Remove compute_range_by_ia method.
Remove mip_cnstr_a, mip_cnstr_b stored in ReluSecondOrderControlAffineSystem.

Add ControlAffineSystemConstraintReturn.

---

neural_network_lyapunov/test/test_utils.py
neural_network_lyapunov/utils.py

This binary variable will be used later when we consider the subgradient.

Absolute function MIP constraint uses an additional binary variable for input=0

---

neural_network_lyapunov/test/test_utils.py
neural_network_lyapunov/utils.py

The previous implementation requires that the point is on the corner of the box, instead on the face boundary.

fix a bug in box_boundary().

---

neural_network_lyapunov/integrator.py
neural_network_lyapunov/test/test_integrator.py

Emulate continuous-time integration with piecewise constant control.

Add rk4_constant_control.

---

.github/workflows/pythonapp.yml
.gitignore
neural_network_lyapunov/examples/pole/pole.py
neural_network_lyapunov/examples/pole/test/test_pole.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/stanfordasl/neural-network-lyapunov/400)

Add Pole class with dynamics.

---

neural_network_lyapunov/relu_to_optimization.py

This function will be used later when we verify continuous time system with a tighter bounds.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/stanfordasl/neural-network-lyapunov/402)

factor out output_gradient_times_vector_w_bounds.

---

neural_network_lyapunov/lyapunov.py
neural_network_lyapunov/test/test_lyapunov.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/stanfordasl/neural-network-lyapunov/403)

Add lyapunov_gradient function.

---

neural_network_lyapunov/examples/pole/pole_relu_system.py
neural_network_lyapunov/examples/pole/test/test_pole_relu_system.py

The system approximates the dynamics of pole/end-effector system using ReLU networks
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/stanfordasl/neural-network-lyapunov/401)

Add PoleReluSystem.

---

neural_network_lyapunov/continuous_time_lyapunov.py
neural_network_lyapunov/test/test_continuous_time_lyapunov.py

Add lyapunov_derivative function.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/stanfordasl/neural-network-lyapunov/404)

start to work on lyapunov for continuous time system.

---

neural_network_lyapunov/hybrid_linear_system.py
neural_network_lyapunov/relu_system.py
neural_network_lyapunov/test/test_relu_system.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/stanfordasl/neural-network-lyapunov/408)

Compute bounds for x_next in AutonomousReLUSystem.

---

neural_network_lyapunov/relu_system.py
neural_network_lyapunov/test/test_relu_system.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/stanfordasl/neural-network-lyapunov/409)

Add discrete_time_flag to AutonomousReLUSystemGivenEquilibrium

---

neural_network_lyapunov/relu_system.py
neural_network_lyapunov/test/test_relu_system.py

Also compute the bounds for x_next.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/stanfordasl/neural-network-lyapunov/410)

Add add_dynamic_constraint to AutonomousReLUGivenEquilibrium.

---

neural_network_lyapunov/relu_system.py
neural_network_lyapunov/test/test_relu_system.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/stanfordasl/neural-network-lyapunov/413)

Add discrete_time_flag to relu system with residue dynamics.

---

neural_network_lyapunov/examples/pole/learn_relu_dynamics.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/stanfordasl/neural-network-lyapunov/412)

Learn a relu model to approximate the Pole dynamics

---

neural_network_lyapunov/relu_system.py
neural_network_lyapunov/test/test_relu_system.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/stanfordasl/neural-network-lyapunov/414)

Add add_dynamic_constraint() function to relu residue dynamics

---

neural_network_lyapunov/hybrid_linear_system.py
neural_network_lyapunov/lyapunov.py
neural_network_lyapunov/relu_system.py
neural_network_lyapunov/test/test_relu_system.py

Use DynamicsConstraintReturn
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/stanfordasl/neural-network-lyapunov/415)

Remove SystemDynamicsConstraintReturn.

---

neural_network_lyapunov/continuous_time_lyapunov.py
neural_network_lyapunov/test/test_continuous_time_lyapunov.py

Currently doesn't include the derivative from V_lambda * |R * (x-x*)|_1
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/stanfordasl/neural-network-lyapunov/416)

Formulate the lyapunov derivative condition as MILP in continuous time.

---

neural_network_lyapunov/continuous_time_lyapunov.py
neural_network_lyapunov/test/test_continuous_time_lyapunov.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/stanfordasl/neural-network-lyapunov/417)

add dl1dx_times_xdot to lyapunov_derivative_as_milp

---

neural_network_lyapunov/continuous_time_lyapunov.py
neural_network_lyapunov/hybrid_linear_system.py
neural_network_lyapunov/relu_system.py
neural_network_lyapunov/test/test_continuous_time_lyapunov.py

Adds relu_binary to the programto compute the Wz bounds.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/stanfordasl/neural-network-lyapunov/418)

Fix a bug computing Wz bounds for lyapunov derivative.

---

neural_network_lyapunov/continuous_time_lyapunov.py
neural_network_lyapunov/test/test_continuous_time_lyapunov.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/stanfordasl/neural-network-lyapunov/419)

Compute the loss of the lyapunov derivative for continuous time system.

---

neural_network_lyapunov/examples/pole/pole_relu_system.py
neural_network_lyapunov/examples/pole/test/test_pole_relu_system.py
neural_network_lyapunov/examples/pole/train_pole_lyapunov.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/stanfordasl/neural-network-lyapunov/420)

Add a file to train the Lyapunov controller for pole/ee system.

---

neural_network_lyapunov/examples/pendulum/pendulum.py
neural_network_lyapunov/examples/pendulum/test/test_pendulum.py
neural_network_lyapunov/test/test_feedback_system.py

Write the continuous-time pendulum dynamics using relu network.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/stanfordasl/neural-network-lyapunov/422)

Add PendulumReluContinuousTime system.

---

neural_network_lyapunov/examples/pendulum/pendulum.py
neural_network_lyapunov/examples/pendulum/test/test_pendulum.py
neural_network_lyapunov/mip_utils.py
neural_network_lyapunov/relu_system.py

Compute the bound of xdot from both IA and optimization method.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/stanfordasl/neural-network-lyapunov/424)

Add bounds when computing pendulum dynamics.

---

neural_network_lyapunov/examples/quadrotor3d/quadrotor_feedback_system.py
neural_network_lyapunov/feedback_system.py
neural_network_lyapunov/mip_utils.py
neural_network_lyapunov/relu_to_optimization.py
neural_network_lyapunov/test/test_feedback_system.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/stanfordasl/neural-network-lyapunov/425)

Add bound prog in the return of controller mip constraint.

---

neural_network_lyapunov/examples/pendulum/test/test_pendulum.py
neural_network_lyapunov/examples/quadrotor3d/quadrotor.py
neural_network_lyapunov/feedback_system.py
neural_network_lyapunov/hybrid_linear_system.py
neural_network_lyapunov/relu_system.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/stanfordasl/neural-network-lyapunov/426)

FeedbackSystem add_dynamic_constraint() also returns the bound prog.

---

neural_network_lyapunov/examples/pendulum/pendulum.py
neural_network_lyapunov/examples/pendulum/test/test_pendulum.py
neural_network_lyapunov/lyapunov.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/stanfordasl/neural-network-lyapunov/427)

Lyapunov::add_system_constraint returns the bound as well.

---

neural_network_lyapunov/examples/pendulum/train_continuous_pendulum_demo.py
neural_network_lyapunov/train_lyapunov.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/stanfordasl/neural-network-lyapunov/423)

WIP: train continuous time pendulum.

---

neural_network_lyapunov/examples/pendulum/test/test_pendulum.py
neural_network_lyapunov/examples/pendulum/train_continuous_pendulum_demo.py

Also increase the torque limit and exponential convergence rate.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/stanfordasl/neural-network-lyapunov/428)

Simulate the continuous-time pendulum.

---

neural_network_lyapunov/examples/quadrotor2d/quadrotor2d_env.py
neural_network_lyapunov/examples/quadrotor2d/quadrotor_2d.py
neural_network_lyapunov/examples/quadrotor2d/test/test_quadrotor_2d.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/stanfordasl/neural-network-lyapunov/429)

Add continuous-time Relu system for 2D quadrotor.

---

neural_network_lyapunov/examples/quadrotor2d/train_continuous_quadrotor_2d_demo.py
neural_network_lyapunov/feedback_system.py

It is a lot harder than the discrete-time case.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/stanfordasl/neural-network-lyapunov/430)

Train continuous-time 2d quadrotor.

---

neural_network_lyapunov/continuous_time_lyapunov.py
neural_network_lyapunov/examples/quadrotor2d/train_continuous_quadrotor_2d_demo.py
neural_network_lyapunov/train_lyapunov.py

It is very hard to decrease the Vdot violation, even in the adversarial training case on finite number of samples.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/stanfordasl/neural-network-lyapunov/431)

Compute Vdot loss for continuous time Lyapunov in a batch.

---

neural_network_lyapunov/barrier.py
neural_network_lyapunov/test/test_barrier.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/stanfordasl/neural-network-lyapunov/432)

Add Barrier class.

---

neural_network_lyapunov/barrier.py
neural_network_lyapunov/test/test_barrier.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/stanfordasl/neural-network-lyapunov/434)

Compute -epsilon*h - hdot

---

neural_network_lyapunov/barrier.py
neural_network_lyapunov/test/test_barrier.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/stanfordasl/neural-network-lyapunov/435)

Add derivative_loss_at_samples for barrier.

---

neural_network_lyapunov/examples/car/train_acceleration_car_demo.py
neural_network_lyapunov/examples/car/train_unicycle_demo.py
neural_network_lyapunov/examples/pendulum/train_continuous_pendulum_demo.py
neural_network_lyapunov/examples/pendulum/train_pendulum_demo.py
neural_network_lyapunov/examples/pole/train_pole_lyapunov.py
neural_network_lyapunov/examples/quadrotor2d/train_continuous_quadrotor_2d_demo.py
neural_network_lyapunov/examples/quadrotor2d/train_quadrotor_2d_demo.py
neural_network_lyapunov/examples/quadrotor3d/train_quadrotor_demo.py
neural_network_lyapunov/examples/quadrotorpx4/train_quadrotor_px4_demo.py
neural_network_lyapunov/examples/rocket/train_rocket_demo.py
neural_network_lyapunov/test/debug_gradient.py
neural_network_lyapunov/test/feedback_gradient_check.py
neural_network_lyapunov/test/synthesize_controller_hybrid_system_demo.py
neural_network_lyapunov/test/test_train_feedback_system.py
neural_network_lyapunov/test/test_train_lyapunov_barrier.py
neural_network_lyapunov/test/train_continuous_linear_system_toy_lyapunov.py
neural_network_lyapunov/test/train_discrete_1d_lyapunov.py
neural_network_lyapunov/test/train_discrete_linear_system_toy_lyapunov.py
neural_network_lyapunov/test/train_toy_second_order_system_controller_demo.py
neural_network_lyapunov/test/train_toy_system_controller_demo.py
neural_network_lyapunov/train_lyapunov_barrier.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/stanfordasl/neural-network-lyapunov/436)

rename train_lyapunov to train_lyapunov_barrier

---

README.md
neural_network_lyapunov/continuous_time_lyapunov.py
neural_network_lyapunov/examples/car/acceleration_car.py
neural_network_lyapunov/examples/car/test/test_unicycle.py
neural_network_lyapunov/examples/car/unicycle.py
neural_network_lyapunov/examples/car/unicycle_feedback_system.py
neural_network_lyapunov/examples/pole/pole_relu_system.py
neural_network_lyapunov/examples/quadrotor3d/quadrotor.py
neural_network_lyapunov/feedback_system.py
neural_network_lyapunov/gurobi_torch_mip.py
neural_network_lyapunov/lyapunov.py
neural_network_lyapunov/mip_utils.py
neural_network_lyapunov/relu_system.py
neural_network_lyapunov/relu_to_optimization.py
neural_network_lyapunov/relu_to_optimization_utils.py
neural_network_lyapunov/test/test_continuous_time_lyapunov.py
neural_network_lyapunov/test/test_feedback_system.py
neural_network_lyapunov/test/test_gurobi_torch_mip.py
neural_network_lyapunov/test/test_lyapunov_roa.py
neural_network_lyapunov/test/test_relu_system.py
neural_network_lyapunov/test/test_relu_to_optimization.py
neural_network_lyapunov/test/test_relu_to_optimization_utils.py
neural_network_lyapunov/utils.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/stanfordasl/neural-network-lyapunov/438)

Fix some test after upgrading gurobi from 9.0 to 9.5

---

neural_network_lyapunov/barrier.py
neural_network_lyapunov/test/test_train_lyapunov_barrier.py
neural_network_lyapunov/train_lyapunov_barrier.py
neural_network_lyapunov/utils.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/stanfordasl/neural-network-lyapunov/437)

Compute barrier function loss on samples.

---

neural_network_lyapunov/test/test_train_lyapunov_barrier.py
neural_network_lyapunov/train_lyapunov_barrier.py

return the cost and the adversarial states.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/stanfordasl/neural-network-lyapunov/439)

Solve barrier value as MIP.

---

neural_network_lyapunov/test/test_train_lyapunov_barrier.py
neural_network_lyapunov/train_lyapunov_barrier.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/stanfordasl/neural-network-lyapunov/440)

Add solve_barrier_derivative_mip to Trainer

---

neural_network_lyapunov/test/test_train_lyapunov_barrier.py
neural_network_lyapunov/train_lyapunov_barrier.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/stanfordasl/neural-network-lyapunov/442)

Compute loss for barrier training.

---

neural_network_lyapunov/test/train_toy_system_controller_demo.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/StanfordASL/neural-network-lyapunov/448)

Fix a bug on the dimension of toy exampe
